In [37]:
import os
import pandas as pd

In [38]:
df = pd.read_csv("./autotagging_moodtheme.csv")
df.head(10)

,TRACK_ID,ARTIST_ID,ALBUM_ID,PATH,DURATION,TAGS
0,track_0000948,artist_000087,album_000149,48/948.mp3,2127,mood/theme---background
1,track_0000950,artist_000087,album_000149,50/950.mp3,2480,mood/theme---background
2,track_0000951,artist_000087,album_000149,51/951.mp3,1997,mood/theme---background
3,track_0002165,artist_000326,album_000347,65/2165.mp3,2290,mood/theme---film
4,track_0002263,artist_000320,album_000366,63/2263.mp3,4947,mood/theme---melancholic
5,track_0003346,artist_000517,album_000521,46/3346.mp3,1950,mood/theme---calm+mood/theme---melodic
6,track_0003347,artist_000517,album_000521,47/3347.mp3,2018,mood/theme---calm+mood/theme---melodic
7,track_0003348,artist_000517,album_000521,48/3348.mp3,2533,mood/theme---calm+mood/theme---melodic
8,track_0003349,artist_000517,album_000521,49/3349.mp3,2284,mood/theme---calm+mood/theme---melodic
9,track_0003350,artist_000517,album_000521,50/3350.mp3,1947,mood/theme---calm+mood/theme---melodic

In [39]:
df[df.eq("00/985000.mp3").any(axis=1)]

,TRACK_ID,ARTIST_ID,ALBUM_ID,PATH,DURATION,TAGS
5554,track_0985000,artist_428049,album_115967,00/985000.mp3,2561,mood/theme---melodic+mood/theme---travel