In [37]:
import os
import pandas as pd

In [ ]:
import numpy as np

# Shim and Sung (2022) Table 4: Phoneme recognition accuracy (%) of DNN models with different parameter sizes
ref1 = np.array(1.04e6)
ref2 = np.array(3.09e6)
ref3 = np.array(5.04e6)

model1 = np.array([1.05e6, 1.00e6, 1.01e6])
model2 = np.array([3.02e6, 3.06e6, 2.97e6])
model3 = np.array([5.07e6, 5.09e6, 5.08e6])

print(np.average([
    np.abs(ref1 - model1), 
    np.abs(ref2 - model2),
    np.abs(ref3 - model3)
]))


# Mine
ref_mine = np.array(353296)

# CNN, GRU, Attn
# 64, 96, 96
model_mine = np.array([374480, 369968])
print(np.average(np.abs(ref_mine - model_mine)))

# 64, 92, 92
model_mine = np.array([355936, 348400])
print(np.average(np.abs(ref_mine - model_mine)))

# 64, 92, 96
model_mine = np.array([355936, 369968])
print(np.average(np.abs(ref_mine - model_mine)))

46666.666666666664
18928.0
3768.0
9656.0

In [38]:
df = pd.read_csv("./autotagging_moodtheme.csv")
df.head(10)

,TRACK_ID,ARTIST_ID,ALBUM_ID,PATH,DURATION,TAGS
0,track_0000948,artist_000087,album_000149,48/948.mp3,2127,mood/theme---background
1,track_0000950,artist_000087,album_000149,50/950.mp3,2480,mood/theme---background
2,track_0000951,artist_000087,album_000149,51/951.mp3,1997,mood/theme---background
3,track_0002165,artist_000326,album_000347,65/2165.mp3,2290,mood/theme---film
4,track_0002263,artist_000320,album_000366,63/2263.mp3,4947,mood/theme---melancholic
5,track_0003346,artist_000517,album_000521,46/3346.mp3,1950,mood/theme---calm+mood/theme---melodic
6,track_0003347,artist_000517,album_000521,47/3347.mp3,2018,mood/theme---calm+mood/theme---melodic
7,track_0003348,artist_000517,album_000521,48/3348.mp3,2533,mood/theme---calm+mood/theme---melodic
8,track_0003349,artist_000517,album_000521,49/3349.mp3,2284,mood/theme---calm+mood/theme---melodic
9,track_0003350,artist_000517,album_000521,50/3350.mp3,1947,mood/theme---calm+mood/theme---melodic

In [39]:
df[df.eq("00/985000.mp3").any(axis=1)]

,TRACK_ID,ARTIST_ID,ALBUM_ID,PATH,DURATION,TAGS
5554,track_0985000,artist_428049,album_115967,00/985000.mp3,2561,mood/theme---melodic+mood/theme---travel